export const NavbarComponents = [
  {
    key: "services",
    title: "Services",
    href: "/services",
    submenu: [
      { title: "Product Engineering" },
      { title: "Discover & Frame Workshop" },
      { title: "Software Development" },
      { title: "Software Testing" },
      { title: "Managed Cloud Services" },
      { title: "Support & Maintenance" },
      { title: "Smart Teams" },
      { title: "Dedicated Teams" },
      { title: "Offshore Development Center" },
      { title: "Enterprise Services" },
      { title: "Technology Consulting" },
      { title: "Robotic Process Automation" },
      { title: "Legacy Modernization" },
      { title: "Enterprise Mobility" },
      { title: "ECM Solutions" },
    ],
  },
  {
    key: "industries",
    title: "Industries",
    href: "/industries",
    submenu: [
      { title: "Healthcare Software & Technology" },
      { title: "Fintech" },
      { title: "Banking" },
      { title: "Real Estate" },
      { title: "Travel & Transportation" },
      { title: "Public Sector" },
      { title: "Media & Entertainment" },
    ],
  },
  {
    key: "expertise",
    title: "Our Expertise",
    href: "/expertise",
    submenu: [
      { title: "Mobile Apps" },
      { title: "UI/UX Design" },
      { title: "Digital Commerce" },
      { title: "DevOps" },
      { title: "Cloud" },
      { title: "Artificial Intelligence" },
      { title: "Data Enrichment" },
      { title: "Digital Transformation" },
      { title: "Internet of Things" },
      { title: "Blockchain" },
      { title: "OTT Platforms" },
      { title: "eLearning Solutions" },
      { title: "Salesforce" },
      { title: "Business Intelligence" },
      { title: "Managed IT Services" },
      { title: "AWS Services" },
      { title: "Application Security" },
      { title: "Digital Marketing" },
    ],
  },
];
